region          = "us-east-1"
aws_profile     = "arn:aws:iam::xxxxxxxxxx:user/xxxxxxxxx-tf-local-exec"
environment     = "sandbox"
initial_db_name = "xxxxxxxDatabase"
master_password = "xxxxxxxxxxxxxxx"
master_username = "rordakadmin"
